[2017-01-23 16:11:54 main] error
[2017-01-23 16:12:22 main] error
[2017-01-23 16:12:40 main] error
[2017-01-23 17:00:19 main] error
[2017-01-23 17:00:50 main] error
[2017-01-23 17:11:21 main] error
[2017-01-23 17:12:57 main] error
[2017-01-23 17:14:39 main main] error
[2017-01-23 17:16:41 main] error
[2017-01-23 17:17:05 main] error
[2017-01-23 17:19:26 main] error
[2017-01-23 17:19:31 main] error
[2017-01-23 17:25:42 main] error
[2017-01-23 17:25:42 main] java.lang.Exception: this is an Exception
	at log.Log4jTest.getStackTrace(Log4jTest.java:65)
	at log.Log4jTest.log4jTest(Log4jTest.java:58)
	at log.Log4jTest.main(Log4jTest.java:82)

[2017-01-23 17:26:36 main] class:=root : error
[2017-01-23 17:26:36 main] class:=root : java.lang.Exception: this is an Exception
	at log.Log4jTest.getStackTrace(Log4jTest.java:65)
	at log.Log4jTest.log4jTest(Log4jTest.java:58)
	at log.Log4jTest.main(Log4jTest.java:82)

[2017-01-24 10:37:17 main] class:=root : error
[2017-01-24 10:37:17 main] class:=root : java.lang.Exception: this is an Exception
	at log.Log4jTest.getStackTrace(Log4jTest.java:65)
	at log.Log4jTest.log4jTest(Log4jTest.java:58)
	at log.Log4jTest.main(Log4jTest.java:82)

